In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
grid = [[0] *  10] * 10
grid

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [3]:
def display_grid():
    for row in grid:
        print(*row)

In [4]:
display_grid()

0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0


In [5]:
squares = {0: '\u2b1c', 1: '\u2b1b'}

In [6]:
'\u2b1c', '\u2b1b'

('⬜', '⬛')

In [7]:
def display_grid():
    for row in grid:
        print(''.join(squares[e] for e in row))

In [8]:
display_grid()

⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜


In [9]:
from random import random

In [10]:
density = 0.2

In [11]:
random()

0.06869219332232668

In [12]:
for i in range(10):
    for j in range(10):
        if random()< density:
            grid[i][j] = 1

In [13]:
display_grid()

⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛
⬛⬛⬛⬛⬜⬛⬛⬛⬛⬛


In [14]:
L = [[0] *10 for _ in range(10)] # every row is unique , not element
L

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [19]:
L = [[0 for _ in range(10)] for _ in range(10)] # every row and element  is unique 
L

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [54]:
grid = [[0 for _ in range(10)] for _ in range(10)]

for i in range(10):
    for j in range(10):
        if random()< density:
            grid[i][j] = 1

display_grid()


⬛⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬛⬜
⬛⬜⬜⬜⬜⬛⬛⬛⬜⬜
⬜⬜⬜⬛⬛⬜⬛⬜⬜⬜
⬜⬛⬜⬜⬛⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬛⬛⬜⬜⬜⬜⬛⬜⬜


In [62]:
grid = [[None for _ in range(10)] for _ in range(10)]

for i in range(10):
    for j in range(10):
        grid[i][j] = int(random() < density)

display_grid()


⬜⬜⬛⬜⬜⬜⬜⬜⬛⬜
⬜⬜⬜⬜⬜⬜⬛⬜⬜⬜
⬜⬛⬜⬜⬜⬛⬜⬜⬜⬜
⬛⬜⬜⬜⬜⬛⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬛⬛
⬜⬜⬜⬜⬜⬜⬛⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬛⬛⬜⬜⬜⬜⬜⬜⬜⬜
⬛⬜⬜⬜⬜⬜⬜⬛⬛⬜
⬛⬛⬜⬜⬛⬜⬜⬜⬛⬜


In [71]:
# Least time complexity
grid = [[int(random() < density) for _ in range(10)] for _ in range(10)] 

display_grid()


⬜⬜⬜⬜⬜⬛⬜⬜⬜⬜
⬛⬜⬜⬜⬜⬜⬜⬜⬛⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬛⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬛⬛⬜⬜⬛⬜⬜⬛⬜
⬜⬜⬜⬜⬛⬛⬛⬜⬛⬜
⬜⬜⬜⬜⬜⬛⬜⬜⬛⬜
⬜⬜⬛⬜⬜⬜⬜⬛⬜⬜
⬛⬜⬜⬜⬜⬜⬜⬜⬜⬜


In [79]:
def evolve():
    global grid
    new_grid = [[0 for _ in range(10)] for _ in range(10)]

    nb_of_neighbour = 0

    for i in range(10):
        for j in range(10):
            # NW
            if i and j and grid[i-1][j-1]: 
                nb_of_neighbour += 1
            # N
            if i and grid[i-1][j]: 
                nb_of_neighbour += 1
            # NE
            if i and j < 9 and grid[i-1][j+1]: 
                nb_of_neighbour += 1
            # SW
            if i < 8 and j and grid[i+1][j-1]: 
                nb_of_neighbour += 1
            # S
            if i < 8 and grid[i+1][j]: 
                nb_of_neighbour += 1
            # SE
            if i < 8 and j < 9 and grid[i+1][j+1]: 
                nb_of_neighbour += 1
            # W
            if j and grid[i][j-1]: 
                nb_of_neighbour += 1
            # E
            if i < 9 and grid[i-1][j-1]: 
                nb_of_neighbour += 1
            if nb_of_neighbour == 3 or nb_of_neighbour == 2 and grid[i][j]:
                new_grid[i][j] = 1

    grid = new_grid 


In [80]:
evolve()
display_grid()

⬜⬜⬜⬛⬛⬛⬛⬛⬛⬛
⬛⬛⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜


In [83]:
def evolve():
    global grid
    new_grid = [[0]* 10 for _ in range(10)]

    for i in range(10):
        for j in range(10):
            nb_of_neighbour = 0 
            # NW
            if i and j and grid[i-1][j-1]: 
                nb_of_neighbour += 1
            # N
            if i and grid[i-1][j]: 
                nb_of_neighbour += 1
            # NE
            if i and j < 9 and grid[i-1][j+1]: 
                nb_of_neighbour += 1
            # SW
            if i < 8 and j and grid[i+1][j-1]: 
                nb_of_neighbour += 1
            # S
            if i < 8 and grid[i+1][j]: 
                nb_of_neighbour += 1
            # SE
            if i < 8 and j < 9 and grid[i+1][j+1]: 
                nb_of_neighbour += 1
            # W
            if j and grid[i][j-1]: 
                nb_of_neighbour += 1
            # E
            if i < 9 and grid[i-1][j-1]: 
                nb_of_neighbour += 1
            if nb_of_neighbour == 3 or nb_of_neighbour == 2 and grid[i][j]:
                new_grid[i][j] = 1

    grid = new_grid 


In [124]:
grid = [[int(random() < density) for _ in range(10)] for _ in range(10)] 

display_grid()
print()
evolve()
display_grid()



⬜⬜⬜⬜⬜⬜⬛⬜⬜⬜
⬛⬜⬜⬛⬛⬜⬜⬛⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜⬜⬛
⬜⬛⬜⬛⬜⬜⬜⬜⬜⬛
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬛⬜⬜⬜⬜⬛⬜⬜⬛⬜
⬜⬛⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬛⬜⬜⬜⬛⬜
⬜⬜⬜⬜⬜⬛⬜⬜⬛⬜

⬜⬜⬜⬜⬜⬜⬛⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬜
⬜⬛⬜⬜⬛⬜⬜⬜⬛⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬛⬜⬛⬜⬛⬜⬜⬜⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜⬜⬛
⬜⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜


In [125]:
evolve()
display_grid()


⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬛⬜
⬜⬜⬛⬛⬜⬜⬜⬜⬜⬜
⬜⬛⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬛⬛⬛⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬛⬜⬜⬜⬜⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜


In [136]:
dim = 10 
frammed_grid = [[0] * (dim + 2) for _ in range(dim + 2)]
frammed_grid

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [137]:
for i in range(1, dim + 1):
    for j in range(1, dim + 1):
        frammed_grid[i][j] = int(random() < density)
frammed_grid


[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [146]:
def display_within_frammed_grid():
    for row in frammed_grid[1:-1]:
        print(''.join(squares[e] for e in row))

In [147]:
display_within_frammed_grid()   

⬜⬜⬜⬜⬜⬜⬜⬛⬜⬛⬜⬜
⬜⬜⬜⬜⬛⬛⬜⬜⬛⬛⬜⬜
⬜⬜⬜⬜⬜⬛⬛⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬛⬛⬛⬛⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬜⬜⬜⬛⬜⬜⬛⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬛⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬛⬜⬜⬛⬛⬜
⬜⬜⬜⬜⬜⬜⬛⬜⬜⬛⬜⬜


In [206]:
framed_grid = [[0] * (dim + 2) for _ in range(dim + 2)]
for i in range(1, dim + 1):
    for j in range(1, dim + 1):
        framed_grid[i][j] = int(random() < density)

def display_population_within_frame(grid):
    squares = {0: '\u2b1c', 1: '\u2b1b'}
    for i in range(1, dim + 1):
        print(''.join(f'{squares[grid[i][j]]}'
                              for j in range(1, dim + 1)
                     )
             )

def next_generation_within_frame():
    global framed_grid
    new_framed_grid = [[0] * (dim + 2) for _ in range(dim + 2)]
    for i in range(1, dim + 1):
        for j in range(1, dim + 1):
            nb_of_neighbours = sum((framed_grid[i - 1][j - 1],
                                    framed_grid[i - 1][j],
                                    framed_grid[i - 1][j + 1],
                                    framed_grid[i][j - 1],
                                    framed_grid[i][j + 1],
                                    framed_grid[i + 1][j - 1],
                                    framed_grid[i + 1][j],
                                    framed_grid[i + 1][j + 1]
                                   )
                                  )
            new_framed_grid[i][j] = int(framed_grid[i][j]
                                        and nb_of_neighbours == 2
                                        or nb_of_neighbours == 3
                                       )
    framed_grid = new_framed_grid


In [184]:
import numpy as np  

In [185]:
np.array([1,4,6,7])

array([1, 4, 6, 7])

In [186]:
a = np.array([1,4,6,7])
a[1]

np.int64(4)

In [199]:
a = np.arange(1, 9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [201]:
a.reshape(2,4)
a.reshape(2,4).T
a.reshape(4,2)



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [203]:
a.reshape(2,4)[1,2] = 70
a

array([ 1,  2,  3,  4,  5,  6, 70,  8])

In [205]:
a.reshape(2,2,2)[1,0,1] = 100
a

array([  1,   2,   3,   4,   5, 100,  70,   8])

In [208]:
L = np.array(range(16)).reshape(2, 8)

L
L[1, 2]
L[1, :]
L[1 : 2, :]
L[:, 3]
L[:, 3 : 4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

np.int64(10)

array([ 8,  9, 10, 11, 12, 13, 14, 15])

array([[ 8,  9, 10, 11, 12, 13, 14, 15]])

array([ 3, 11])

array([[ 3],
       [11]])

In [ ]:
 L = np.array(range(16)).reshape(2, 2, 4)

L
L[1, 0, 2]
L[1, 1, 1 :]
L[1, :, 1 : 3]
L[0 : 1, 0 : 1, 1 : 3]
