In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [4]:
import numpy as np

In [6]:
L = np.array(range(16)).reshape(2, 2, 4)

L
L[1, 0, 2]
L[1, 1, 1 :]
L[1, :, 1 : 3]
L[0 : 1, 0 : 1, 1 : 3]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

np.int64(10)

array([13, 14, 15])

array([[ 9, 10],
       [13, 14]])

array([[[1, 2]]])

In [8]:
L = np.array(range(1,5)).reshape(2, 2)
L

array([[1, 2],
       [3, 4]])

In [7]:
L1 = np.array([10,20]).reshape(2, 1)
L1

array([[10],
       [20]])

In [9]:
L + L1

array([[11, 12],
       [23, 24]])

In [14]:
L1 = np.arange(10,50,10).reshape(2, 2)
L1

array([[10, 20],
       [30, 40]])

In [11]:
L @ L1

array([[ 50],
       [110]])

In [16]:
L1 = np.array([0,2,1,0]).reshape(2, 2)
L2  = np.array([0,0,3,4]).reshape(2, 2) 
L1
L2

array([[0, 2],
       [1, 0]])

array([[0, 0],
       [3, 4]])

In [17]:
np.logical_and(L1, L2)

array([[False, False],
       [ True, False]])

In [18]:
np.logical_and(L1, L2).astype(int)

array([[0, 0],
       [1, 0]])

In [19]:
np.logical_or(L1, L2).astype(int)

array([[0, 1],
       [1, 1]])

In [3]:
from random import random 
import numpy as np

In [4]:
dim =10
density = 0.2

In [12]:
# framed_grid = [[0] * (dim + 2) for _ in range(dim + 2)]
framed_grid = np.zeros((dim + 2, dim + 2),int)
for i in range(1, dim + 1):
    for j in range(1, dim + 1):
        framed_grid[i,j] = int(random() < density)

def display_population_within_frame(grid):
    squares = {0: '\u2b1c', 1: '\u2b1b'}
    for i in range(1, dim + 2):
        print(''.join(f'{squares[grid[i][j]]}'
                              for j in range(1, dim + 2)
                     )
             )

def framed_evolve():
    global framed_grid
    new_grid =  np.zeros((dim + 2, dim + 2),int)
    N = framed_grid[:-2, 1:-1]
    S = framed_grid[2:, 1:-1]
    E = framed_grid[1:-1, 2:]
    W = framed_grid[1:-1, :-2]
    NE = framed_grid[:-2, 2:]
    NW = framed_grid[:-2, :-2]
    SE = framed_grid[2:, 2:]   
    SW = framed_grid[2:, :-2]
    nb_of_neighbours =  N + S + E + W + NE + NW + SE + SW  
    new_grid[1:-1, 1:-1]  = nb_of_neighbours
    framed_grid = np.logical_or(nb_of_neighbours == 3 , np.logical_and( nb_of_neighbours == 2, nb_of_neighbours ==1 )).astype(int)
    


In [13]:
display_population_within_frame(framed_grid)
print()

framed_evolve()
display_population_within_frame(framed_grid)
print()

framed_evolve()
display_population_within_frame(framed_grid)

⬜⬛⬜⬜⬜⬛⬛⬛⬜⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬛⬜⬜⬜⬛⬛⬛⬜⬜
⬜⬜⬜⬜⬜⬜⬛⬜⬜⬜⬜
⬛⬜⬛⬜⬜⬜⬜⬜⬜⬛⬜
⬛⬜⬛⬜⬜⬜⬜⬜⬛⬜⬜
⬜⬜⬜⬛⬜⬜⬛⬜⬜⬜⬜
⬜⬜⬛⬜⬛⬜⬜⬜⬜⬜⬜
⬜⬛⬜⬜⬜⬜⬜⬜⬛⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬛⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜⬜



IndexError: index 10 is out of bounds for axis 0 with size 10

In [31]:
np.zeros((dim + 2, dim + 2))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
L = np.array(range(4)).reshape(2, 2)
L
L == 2


array([[0, 1],
       [2, 3]])

array([[False, False],
       [ True, False]])

In [35]:
def f():
    yield 0
    yield 1

g = f()
next(g),next(g)

(0, 1)

In [39]:
def f(x):
    while True:
        yield x
        if x%2 == 0:
            x //= 2
        else:
            x = 3*x + 1

In [42]:
I = f(100)
[next(I) for _ in range(35)]

[100,
 50,
 25,
 76,
 38,
 19,
 58,
 29,
 88,
 44,
 22,
 11,
 34,
 17,
 52,
 26,
 13,
 40,
 20,
 10,
 5,
 16,
 8,
 4,
 2,
 1,
 4,
 2,
 1,
 4,
 2,
 1,
 4,
 2,
 1]

In [43]:
def f():
    x = 0
    while True:
        yield x
        x += 1
I = f()
[next(I) for _ in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]